j8y18lte: drop non-exist include path system/core/base/include
 Error:
 error: device/samsung/j8y18lte/init/Android.bp:1:1: module "libinit_j8y18lte" variant "android_arm_armv8-a_cortex-a53_static": source path "
 system/core/base/include" does not exist

Signed-off-by: Ayush Bisht <ayushbisht5663@gmail.com>